
spring:
    datasource:
        # url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul
        # username: root
        # password: 1234
        url: jdbc:mysql://awseb-e-sjsm5xchph-stack-awsebrdsdatabase-z6bus2ept7zc.cergqkr1obpv.ap-northeast-2.rds.amazonaws.com:3306?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: dks4268!
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.format_sql: true
